using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using CSharpAmazonBusinessAPI.Exceptions;
using Newtonsoft.Json;

namespace CSharpAmazonBusinessAPI.Authentication
{
    // Helpers for the LWA "authorization code" grant — used during one-time onboarding when
    // a SaaS app or App Center listing collects a customer's Amazon Business consent and
    // exchanges the resulting code for a long-lived refresh_token. Once you have the refresh
    // token, persist it and pass it to AmazonBusinessCredential going forward.
    //
    // Two flows use this:
    //   - Website authorization workflow:
    //     https://developer-docs.amazon.com/amazon-business/docs/website-authorization-workflow
    //   - App Center authorization workflow:
    //     https://developer-docs.amazon.com/amazon-business/docs/app-center-authorization-workflow
    //
    // For the steady-state refresh_token → access_token exchange used on every API call,
    // see LwaClient (driven by AmazonBusinessConnection internally).
    public static class LwaConsentHelper
    {
        // Standard LWA endpoints — same as for SP-API and any other Login-with-Amazon app.
        public const string AuthorizationEndpoint = "https://www.amazon.com/ap/oa";
        public const string TokenEndpoint = LwaClient.TokenEndpoint;

        // Builds the consent URL. Direct the customer's browser here; on consent Amazon
        // redirects to `redirectUri?code=...&state=...`. The `state` value is generated by
        // the caller (use a short-lived per-request nonce) and is echoed back unchanged —
        // verify it on return to defend against CSRF.
        public static string BuildAuthorizationUrl(
            string clientId,
            string redirectUri,
            string state,
            string scope = "profile")
        {
            if (string.IsNullOrEmpty(clientId)) throw new ArgumentException("clientId required", nameof(clientId));
            if (string.IsNullOrEmpty(redirectUri)) throw new ArgumentException("redirectUri required", nameof(redirectUri));
            if (string.IsNullOrEmpty(state)) throw new ArgumentException("state required (CSRF guard)", nameof(state));

            var query = new[]
            {
                "client_id=" + Uri.EscapeDataString(clientId),
                "scope=" + Uri.EscapeDataString(scope),
                "response_type=code",
                "redirect_uri=" + Uri.EscapeDataString(redirectUri),
                "state=" + Uri.EscapeDataString(state),
            };
            return AuthorizationEndpoint + "?" + string.Join("&", query);
        }

        // Exchanges the one-time `code` from Amazon's redirect for an access + refresh token.
        // The `code` expires 5 minutes after issue — call this immediately on receipt.
        public static async Task<LwaTokenResponse> ExchangeCodeForTokensAsync(
            string code,
            string clientId,
            string clientSecret,
            string redirectUri,
            IWebProxy proxy = null,
            CancellationToken cancellationToken = default)
        {
            if (string.IsNullOrEmpty(code)) throw new ArgumentException("code required", nameof(code));
            if (string.IsNullOrEmpty(clientId)) throw new ArgumentException("clientId required", nameof(clientId));
            if (string.IsNullOrEmpty(clientSecret)) throw new ArgumentException("clientSecret required", nameof(clientSecret));
            if (string.IsNullOrEmpty(redirectUri)) throw new ArgumentException("redirectUri required", nameof(redirectUri));

            var handler = new HttpClientHandler();
            if (proxy != null)
            {
                handler.Proxy = proxy;
                handler.UseProxy = true;
            }

            using (var http = new HttpClient(handler))
            {
                var form = new FormUrlEncodedContent(new[]
                {
                    new KeyValuePair<string, string>("grant_type", "authorization_code"),
                    new KeyValuePair<string, string>("code", code),
                    new KeyValuePair<string, string>("client_id", clientId),
                    new KeyValuePair<string, string>("client_secret", clientSecret),
                    new KeyValuePair<string, string>("redirect_uri", redirectUri),
                });

                using (var response = await http.PostAsync(TokenEndpoint, form, cancellationToken).ConfigureAwait(false))
                {
                    var body = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                    if (!response.IsSuccessStatusCode)
                        throw new AmazonBusinessUnauthorizedException(
                            $"LWA code exchange failed: {(int)response.StatusCode} {response.StatusCode}",
                            response.StatusCode, body);

                    return JsonConvert.DeserializeObject<LwaTokenResponse>(body);
                }
            }
        }
    }
}
